# Generated by Django 3.1.3 on 2020-11-22 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'камера',
                'verbose_name_plural': 'камеры',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
            },
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'SPEED'), (1, 'AVERAGE SPEED'), (2, 'RED LIGHT'), (3, 'DOUBLE WHITE LINE'), (4, 'BUS LANE'), (5, 'TOLLBOOTH'), (6, 'LEVEL CROSSING'), (7, 'CONGESTION CHARGE')], verbose_name='тип')),
                ('producer', models.CharField(max_length=100, verbose_name='производитель')),
                ('date_of_manufacture', models.DateField(verbose_name='дата производства')),
                ('service_frequency', models.IntegerField(verbose_name='частота сервисного обслуживания')),
                ('notes', models.TextField(blank=True, default='', verbose_name='заметки')),
            ],
            options={
                'verbose_name': 'спецификация',
                'verbose_name_plural': 'спецификации',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'OK'), (1, 'WARNING'), (2, 'ERROR'), (3, 'FAILURE')], verbose_name='состояние')),
                ('logs', models.TextField(blank=True, default='', verbose_name='журнал')),
            ],
            options={
                'verbose_name': 'состояние',
                'verbose_name_plural': 'состояния',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_organization', models.CharField(max_length=100, verbose_name='сервисная организация')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('service_data', models.DateField(verbose_name='дата сервиса')),
                ('info', models.TextField(blank=True, default='', verbose_name='информация')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.camera', verbose_name='ID камеры')),
            ],
            options={
                'verbose_name': 'сервис',
                'verbose_name_plural': 'сервисы',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, verbose_name='улица')),
                ('support', models.IntegerField(verbose_name='номер опоры')),
                ('notes', models.TextField(blank=True, default='', verbose_name='заметки')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city', verbose_name='город')),
            ],
            options={
                'verbose_name': 'положение',
                'verbose_name_plural': 'положения',
            },
        ),
        migrations.AddField(
            model_name='camera',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.location', verbose_name='местоположение'),
        ),
        migrations.AddField(
            model_name='camera',
            name='specifications',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.specifications', verbose_name='спецификации'),
        ),
        migrations.AddField(
            model_name='camera',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.state', verbose_name='состояние'),
        ),
    ]
